### ISSUE TITLE
bug: Android project failed on open

### ISSUE THREAD

**Issue by enriqueloz88** [robingenz/capacitor-firebase-authentication-demo#164]
**Describe the bug**
When doing the build in android everything works correctly, taking the application key correctly (I have created a file with the following configuration):

```
storePassword=myStorePassword
keyPassword=mykeyPassword
keyAlias=myKeyAlias
storeFile=myStoreFileLocation
```

However, when executing the application, it closes instantly with the following message:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.monekin.app, PID: 2830
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.monekin.app. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
        at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@21.0.1:1)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.<init>(FirebaseAuthentication.java:53)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:25)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:59)
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:503)
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:458)
        at com.getcapacitor.Bridge.<init>(Bridge.java:188)
        at com.getcapacitor.Bridge.<init>(Bridge.java:65)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1288)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436)
        at android.app.Activity.performStart(Activity.java:8190)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3547)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8059)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**To Reproduce**
Just clone the project and compile it in Android Studio

**Comment by robingenz** [comment]
Hi @enriqueloz88,
You need to add your `google-services.json` file from Firebase in `android/app/`.

Does this help?

**Comment by enriqueloz88** [comment]
Thanks! That was the problem.

Now I have another one, I'm researching it:

```
16577-16577/dev.robingenz.capacitor.firebaseauth.demo E/Capacitor/Plugin: 10: 
    com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@19.0.0:9)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.handleOnActivityResult(GoogleAuthProviderHandler.java:44)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.handleGoogleAuthProviderActivityResult(FirebaseAuthentication.java:198)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.handleGoogleAuthProviderActivityResult(FirebaseAuthenticationPlugin.java:163)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.Plugin.triggerActivityCallback(Plugin.java:155)
        at com.getcapacitor.Plugin.lambda$initializeActivityLaunchers$0$Plugin(Plugin.java:117)
        at com.getcapacitor.-$$Lambda$Plugin$9tit0PZrRMA5UA4Z_xqI4yDk4JY.onActivityResult(Unknown Source:6)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:362)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:322)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:634)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:216)
        at android.app.Activity.dispatchActivityResult(Activity.java:8533)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5149)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5197)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8059)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

![Screenshot_2022-03-28-21-49-00-013_dev robingenz capacitor firebaseauth demo](https://user-images.githubusercontent.com/61509169/160475713-d9bc3ea5-436c-4cae-8405-232fc78261f9.jpg)

It seems like a key thing but if I follow these steps it tells me that the key is duplicated https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/147#issuecomment-996541625

```
Duplicate key dev.robingenz.capacitor.firebaseauth.demo.MainActivity (attempted merging values dev/robingenz/capacitor/firebaseauth/demo/MainActivity.java and com/monekin/app/MainActivity.java)
```

**Comment by robingenz** [comment]
The error looks like error code 10 ([DEVELOPER_ERROR](https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes.html#DEVELOPER_ERROR)) from Google Play Services.
Please have a look at this [comment](https://github.com/googlesamples/google-services/issues/360#issuecomment-381648685).
Make sure your app is configured correctly in the Google API Console/Firebase Console (specifically the SHA1) and you have configured the correct package name in https://github.com/robingenz/capacitor-firebase-authentication-demo/blob/main/android/app/src/main/res/values/strings.xml.

Let me know if this helps you.

**Comment by enriqueloz88** [comment]
Thank you very much, as you say it gives me an API 10 error, it will be a matter of how I have the SHA1 keys. I will keep investigating about it.

Thank you very much again!
