### ISSUE TITLE
bug: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process dev.robingenz.capacitor.firebaseauth.demo.

### ISSUE THREAD

**Issue by sirgatsen** [robingenz/capacitor-firebase-authentication-demo#189]
**Describe the bug**

When I try to run the app on an Android device it crashes with the exception: **java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process dev.robingenz.capacitor.firebaseauth.demo. Make sure to call FirebaseApp.initializeApp(Context) first.**

**To Reproduce**

1. `git clone https://github.com/robingenz/capacitor-firebase-authentication-demo.git`
2. `cd capacitor-firebase-authentication-demo`
3. `npx ionic cap sync android`
4. `npx ionic cap run android`

**Expected behavior**

The app should run on the device and demonstrate the firebase authentication

**Screenshots**

![Screen Shot 2022-07-26 at 00 18 39](https://user-images.githubusercontent.com/828654/180884382-baeba2b3-7af6-4e00-8618-5cf820c434b3.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.13.6 High Sierra
- Browser: Chrome
- Version: 103.0.5060.134 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A70 (SM-A705FN/DS)
- OS: Android 11, One UI 3.1
- Browser: Chrome
- Version: 103.0.5060.129

**Additional context**

Ionic:

   Ionic CLI                     : 6.20.1 (/Users/sirgatsen/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.12
   @angular-devkit/build-angular : 14.0.4
   @angular-devkit/schematics    : 13.3.7
   @angular/cli                  : 14.0.4
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : 3.6.0
   @capacitor/core    : 3.6.0
   @capacitor/ios     : 3.6.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.6.0) : 1.5.0

System:

   NodeJS : v16.14.0 (/Users/sirgatsen/.nvm/versions/node/v16.14.0/bin/node)
   npm    : 8.3.1
   OS     : macOS High Sierra

**Comment by sirgatsen** [comment]
Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.13.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (212-1.7.10-release-333-AS5457.46)

**Comment by sirgatsen** [comment]
I initially encountered the error on my own test app (setup specifically to test the firebase-authentication package and then I thought to clone yours and see if I was doing anything wrong but alas same issue.

**Comment by robingenz** [comment]
You need to add your `google-services.json` file.
This is not documented yet (see #2).

**Comment by sirgatsen** [comment]
@robingenz I have added the `google-services.json` file but still continued to experience some other issues (exceptions). 

I did finally manage to get it to run after adding `rgcfaIncludeGoogle = true` in the file `android/variables.gradle`. 

However while running on the device it doesn't seem to complete the authentication flow. I am getting below exception after calling `await FirebaseAuthentication.signInWithGoogle()` and selecting the Google account to use. 

Please advise. I have published my [test repo here](https://github.com/gatsensoft/firebase-auth) if you want to review.

![Screen Shot 2022-07-27 at 23 17 59](https://user-images.githubusercontent.com/828654/181823231-2f9b775c-48c5-47df-9ea4-83bb32ced244.png)

**Comment by robingenz** [comment]
Google Error 10 often indicates a problem with your SHA1 fingerprint which means that you have not added the correct SHA-1 fingerprint in your Firebase Console, see https://stackoverflow.com/a/62231264

**Comment by sirgatsen** [comment]
Thank you sir, I was able to authenticate without further issues after adding the SHA1 fingerprint of my debug certificate. I can't thank you enough for the prompt responses and guidance.

**Comment by robingenz** [comment]
You are welcome! Reach out if you have more questions.

**Comment by ebadi** [comment]
I have the same exact problem. `rgcfaIncludeGoogle = true` was correctly set and changing it to `false` didn't solve the problem:

```
2023-09-02 10:50:22.320 11702-11702 Perf                    dev...z.capacitor.firebaseauth.demo  I  Connecting to perf service.
2023-09-02 10:50:22.332 11702-11702 FirebaseApp             dev...z.capacitor.firebaseauth.demo  W  Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
2023-09-02 10:50:22.332 11702-11702 FirebaseInitProvider    dev...z.capacitor.firebaseauth.demo  I  FirebaseApp initialization unsuccessful
2023-09-02 10:50:22.397 11702-11702 com.facebo...ngsManager dev...z.capacitor.firebaseauth.demo  W  Please set a value for AutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
2023-09-02 10:50:22.397 11702-11702 com.facebo...ngsManager dev...z.capacitor.firebaseauth.demo  W  You haven't set a value for AdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
2023-09-02 10:50:22.419 11702-11740 SharedPreferencesImpl   dev...z.capacitor.firebaseauth.demo  W  Cannot read /data/user/0/dev.robingenz.capacitor.firebaseauth.demo/shared_prefs/com.facebook.internal.preferences.APP_GATEKEEPERS.xml
                                                                                                    org.xmlpull.v1.XmlPullParserException: Unexpected end of document
                                                                                                    	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1402)
                                                                                                    	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:741)
                                                                                                    	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:157)
                                                                                                    	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:55)
                                                                                                    	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:126)
2023-09-02 10:50:22.432 11702-11702 FeatureParser           dev...z.capacitor.firebaseauth.demo  I  can't find gauguin.xml in assets/device_features/,it may be in /vendor/etc/device_features
2023-09-02 10:50:22.432 11702-11743 com.facebo...veProtocol dev...z.capacitor.firebaseauth.demo  W  Apps that target Android API 30+ (Android 11+) cannot call Facebook native apps unless the package visibility needs are declared. Please follow https://developers.facebook.com/docs/android/troubleshooting/#faq_267321845055988 to make the declaration.
2023-09-02 10:50:22.434 11702-11739 NetworkSecurityConfig   dev...z.capacitor.firebaseauth.demo  D  No Network Security Config specified, using platform default
2023-09-02 10:50:22.440 11702-11702 libc                    dev...z.capacitor.firebaseauth.demo  E  Access denied finding property "ro.vendor.df.effect.conflict"
2023-09-02 10:50:22.440 11702-11702 libc                    dev...z.capacitor.firebaseauth.demo  E  Access denied finding property "ro.vendor.knock.type"
2023-09-02 10:50:22.504 11702-11702 AppCompatDelegate       dev...z.capacitor.firebaseauth.demo  D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2023-09-02 10:50:22.559 11702-11702 ForceDarkHelper         dev...z.capacitor.firebaseauth.demo  D  updateByCheckExcludeList: pkg: dev.robingenz.capacitor.firebaseauth.demo activity: dev.robingenz.capacitor.firebaseauth.demo.MainActivity@7b4d9ad
2023-09-02 10:50:22.561 11702-11702 chatty                  dev...z.capacitor.firebaseauth.demo  I  uid=10450(dev.robingenz.capacitor.firebaseauth.demo) identical 1 line
2023-09-02 10:50:22.567 11702-11702 ForceDarkHelper         dev...z.capacitor.firebaseauth.demo  D  updateByCheckExcludeList: pkg: dev.robingenz.capacitor.firebaseauth.demo activity: dev.robingenz.capacitor.firebaseauth.demo.MainActivity@7b4d9ad
2023-09-02 10:50:22.568 11702-11702 ForceDarkHelper         dev...z.capacitor.firebaseauth.demo  D  updateByCheckExcludeList: pkg: dev.robingenz.capacitor.firebaseauth.demo activity: dev.robingenz.capacitor.firebaseauth.demo.MainActivity@7b4d9ad
2023-09-02 10:50:22.570 11702-11702 ForceDarkHelper         dev...z.capacitor.firebaseauth.demo  D  updateByCheckExcludeList: pkg: dev.robingenz.capacitor.firebaseauth.demo activity: dev.robingenz.capacitor.firebaseauth.demo.MainActivity@7b4d9ad
2023-09-02 10:50:22.575 11702-11702 rebaseauth.dem          dev...z.capacitor.firebaseauth.demo  W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2023-09-02 10:50:22.575 11702-11702 rebaseauth.dem          dev...z.capacitor.firebaseauth.demo  W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2023-09-02 10:50:22.582 11702-11702 ForceDarkHelper         dev...z.capacitor.firebaseauth.demo  D  updateByCheckExcludeList: pkg: dev.robingenz.capacitor.firebaseauth.demo activity: dev.robingenz.capacitor.firebaseauth.demo.MainActivity@7b4d9ad
2023-09-02 10:50:22.584 11702-11702 ForceDarkHelper         dev...z.capacitor.firebaseauth.demo  D  updateByCheckExcludeList: pkg: dev.robingenz.capacitor.firebaseauth.demo activity: dev.robingenz.capacitor.firebaseauth.demo.MainActivity@7b4d9ad
2023-09-02 10:50:22.600 11702-11702 WebViewFactory          dev...z.capacitor.firebaseauth.demo  I  Loading com.google.android.webview version 116.0.5845.92 (code 584509231)
2023-09-02 10:50:22.605 11702-11702 linker                  dev...z.capacitor.firebaseauth.demo  W  Warning: "/data/app/com.google.android.webview-12NdaR7QsnRXJR9fhOdZiQ==/base.apk!/lib/arm64-v8a/libmonochrome.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
2023-09-02 10:50:22.625 11702-11702 cr_WVCFactoryProvider   dev...z.capacitor.firebaseauth.demo  I  Loaded version=116.0.5845.92 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
2023-09-02 10:50:22.656 11702-11702 cr_LibraryLoader        dev...z.capacitor.firebaseauth.demo  I  Successfully loaded native library
2023-09-02 10:50:22.656 11702-11702 cr_CachingUmaRecorder   dev...z.capacitor.firebaseauth.demo  I  Flushed 6 samples from 6 histograms, 0 samples were dropped.
2023-09-02 10:50:22.835 11702-11702 EgretLoader             dev...z.capacitor.firebaseauth.demo  D  EgretLoader(Context context)
2023-09-02 10:50:22.836 11702-11702 EgretLoader             dev...z.capacitor.firebaseauth.demo  D  The context is not activity
2023-09-02 10:50:22.842 11702-11702 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Starting BridgeActivity
2023-09-02 10:50:22.866 11702-11702 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Registering plugin instance: CapacitorCookies
2023-09-02 10:50:22.870 11702-11702 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Registering plugin instance: WebView
2023-09-02 10:50:22.871 11702-11702 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Registering plugin instance: CapacitorHttp
2023-09-02 10:50:22.873 11702-11702 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Registering plugin instance: FirebaseAuthentication
2023-09-02 10:50:22.881 11702-11702 AndroidRuntime          dev...z.capacitor.firebaseauth.demo  D  Shutting down VM
2023-09-02 10:50:22.882 11702-11702 AndroidRuntime          dev...z.capacitor.firebaseauth.demo  E  FATAL EXCEPTION: main
                                                                                                    Process: dev.robingenz.capacitor.firebaseauth.demo, PID: 11702
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.robingenz.capacitor.firebaseauth.demo/dev.robingenz.capacitor.firebaseauth.demo.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process dev.robingenz.capacitor.firebaseauth.demo. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7574)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
                                                                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process dev.robingenz.capacitor.firebaseauth.demo. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:186)
                                                                                                    	at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@21.2.0:1)
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.<init>(FirebaseAuthentication.java:66)
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:65)
                                                                                                    	at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115)
                                                                                                    	at com.getcapacitor.PluginHandle.load(PluginHandle.java:105)
                                                                                                    	at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
                                                                                                    	at com.getcapacitor.Bridge.registerPlugin(Bridge.java:644)
                                                                                                    	at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:600)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Bridge.java:213)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$Builder.create(Bridge.java:1519)
                                                                                                    	at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:42)
                                                                                                    	at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:36)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7916)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7903)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3288)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:224) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7574) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2023-09-02 10:50:22.884 11702-11702 MQSEventManagerDelegate dev...z.capacitor.firebaseauth.demo  E  failed to get MQSService.
2023-09-02 10:50:22.890 11702-11702 rebaseauth.dem          dev...z.capacitor.firebaseauth.demo  W  Attempt to remove non-JNI local reference, dumping thread
2023-09-02 10:50:22.884 11702-11702 MQSEventManagerDelegate dev...z.capacitor.firebaseauth.demo  E  failed to get MQSService.
2023-09-02 10:50:22.920 11702-11702 Process                 dev...z.capacitor.firebaseauth.demo  I  Sending signal. PID: 11702 SIG: 9
```
