### ISSUE TITLE
bug: IllegalStateException: Default FirebaseApp is not initialized in this process

### ISSUE THREAD

**Issue by ebadi** [robingenz/capacitor-firebase-authentication-demo#221]
**Describe the bug**
Application crashes on startup

**To Reproduce**
Building the project using android studio 2022.3.1

**Screenshots**

```
2023-10-06 19:20:50.111 14445-14445 cr_LibraryLoader        dev...z.capacitor.firebaseauth.demo  I  Successfully loaded native library
2023-10-06 19:20:50.112 14445-14445 cr_CachingUmaRecorder   dev...z.capacitor.firebaseauth.demo  I  Flushed 6 samples from 6 histograms, 0 samples were dropped.
2023-10-06 19:20:50.341  2937-3051  Launcher.AllAppsList    com.miui.home                        E  Can't load postion for packageName: dev.robingenz.capacitor.firebaseauth.demo activityName: dev.robingenz.capacitor.firebaseauth.demo.MainActivity
2023-10-06 19:20:50.484 14445-14445 EgretLoader             dev...z.capacitor.firebaseauth.demo  D  EgretLoader(Context context)
2023-10-06 19:20:50.486 14445-14445 EgretLoader             dev...z.capacitor.firebaseauth.demo  D  The context is not activity
2023-10-06 19:20:50.492 14445-14445 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Starting BridgeActivity
2023-10-06 19:20:50.518 14445-14445 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Registering plugin instance: CapacitorCookies
2023-10-06 19:20:50.523 14445-14445 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Registering plugin instance: WebView
2023-10-06 19:20:50.525 14445-14445 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Registering plugin instance: CapacitorHttp
2023-10-06 19:20:50.526 14445-14445 Capacitor               dev...z.capacitor.firebaseauth.demo  D  Registering plugin instance: FirebaseAuthentication
2023-10-06 19:20:50.533 14445-14445 AndroidRuntime          dev...z.capacitor.firebaseauth.demo  D  Shutting down VM
2023-10-06 19:20:50.536 14445-14445 AndroidRuntime          dev...z.capacitor.firebaseauth.demo  E  FATAL EXCEPTION: main
                                                                                                    Process: dev.robingenz.capacitor.firebaseauth.demo, PID: 14445
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.robingenz.capacitor.firebaseauth.demo/dev.robingenz.capacitor.firebaseauth.demo.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process dev.robingenz.capacitor.firebaseauth.demo. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7574)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
                                                                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process dev.robingenz.capacitor.firebaseauth.demo. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:186)
                                                                                                    	at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@21.2.0:1)
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.<init>(FirebaseAuthentication.java:66)
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:65)
                                                                                                    	at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115)
                                                                                                    	at com.getcapacitor.PluginHandle.load(PluginHandle.java:105)
                                                                                                    	at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
                                                                                                    	at com.getcapacitor.Bridge.registerPlugin(Bridge.java:644)
                                                                                                    	at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:600)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Bridge.java:213)
                                                                                                    	at com.getcapacitor.Bridge.<init>(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$Builder.create(Bridge.java:1519)
                                                                                                    	at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:42)
                                                                                                    	at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:36)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7916)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7903)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3288)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:224) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7574) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2023-10-06 19:20:50.538 14445-14445 MQSEventManagerDelegate dev...z.capacitor.firebaseauth.demo  E  failed to get MQSService.
2023-10-06 19:20:50.544 14445-14445 rebaseauth.dem          dev...z.capacitor.firebaseauth.demo  W  Attempt to remove non-JNI local reference, dumping thread
2023-10-06 19:20:50.539 14445-14445 MQSEventManagerDelegate dev...z.capacitor.firebaseauth.demo  E  failed to get MQSService.
2023-10-06 19:20:50.590 14445-14445 Process                 dev...z.capacitor.firebaseauth.demo  I  Sending signal. PID: 14445 SIG: 9

```

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04

**Smartphone (please complete the following information):**

 Android 10

**Comment by robingenz** [comment]
You have to add the `google-services.json` file, see https://github.com/capawesome-team/capacitor-firebase/blob/main/docs/firebase-setup.md#add-a-firebase-configuration-file

**Comment by ebadi** [comment]
Thanks. Problem solved.
