### ISSUE TITLE
bug:  main.js - Error: Uncaught (in promise): Error: 10

### ISSUE THREAD

**Issue by ebadi** [robingenz/capacitor-firebase-authentication-demo#222]
**Describe the bug**
Error message after I login. 

**Screenshots**

![photo_2023-10-06_23-21-03 (2)](https://github.com/robingenz/capacitor-firebase-authentication-demo/assets/1111940/195b7457-830b-401c-b8ba-effc0e865724)

![photo_2023-10-06_23-21-13](https://github.com/robingenz/capacitor-firebase-authentication-demo/assets/1111940/5afda9e2-f57e-4510-8b77-306a66fe6498)

```
2023-10-07 00:01:33.167  8113-8113  ActivityThread          dev...z.capacitor.firebaseauth.demo  W  handleWindowVisibility: no activity for token android.os.BinderProxy@44c61f8
2023-10-07 00:01:33.175  8113-8113  Timeline                dev...z.capacitor.firebaseauth.demo  I  Timeline: Activity_launch_request time:257214247
2023-10-07 00:01:33.201  8113-8113  ForceDarkHelper         dev...z.capacitor.firebaseauth.demo  D  updateByCheckExcludeList: pkg: dev.robingenz.capacitor.firebaseauth.demo activity: com.google.android.gms.auth.api.signin.internal.SignInHubActivity@55e541a
2023-10-07 00:01:33.202  8113-8113  chatty                  dev...z.capacitor.firebaseauth.demo  I  uid=10467(dev.robingenz.capacitor.firebaseauth.demo) identical 1 line
2023-10-07 00:01:33.202  8113-8113  ForceDarkHelper         dev...z.capacitor.firebaseauth.demo  D  updateByCheckExcludeList: pkg: dev.robingenz.capacitor.firebaseauth.demo activity: com.google.android.gms.auth.api.signin.internal.SignInHubActivity@55e541a
2023-10-07 00:01:38.986  8113-8113  Capacitor               dev...z.capacitor.firebaseauth.demo  D  Unable to find a Capacitor plugin to handle requestCode, trying Cordova plugins 1936168311
2023-10-07 00:01:38.997  8113-8113  FirebaseAuthentication  dev...z.capacitor.firebaseauth.demo  E  10: 
                                                                                                    com.google.android.gms.common.api.ApiException: 10: 
                                                                                                    	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.0.1:3)
                                                                                                    	at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@20.5.0:3)
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.handleOnActivityResult(GoogleAuthProviderHandler.java:56)
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.handleGoogleAuthProviderSignInActivityResult(FirebaseAuthentication.java:594)
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.handleGoogleAuthProviderSignInActivityResult(FirebaseAuthenticationPlugin.java:823)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.Plugin.triggerActivityCallback(Plugin.java:155)
                                                                                                    	at com.getcapacitor.Plugin.lambda$initializeActivityLaunchers$0(Plugin.java:117)
                                                                                                    	at com.getcapacitor.Plugin.$r8$lambda$eMEw5HOEwzweqoelVfHBIM3lIww(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Plugin$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:6)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
                                                                                                    	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:818)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:152)
                                                                                                    	at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:172)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8274)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:4943)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4991)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7574)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2023-10-07 00:01:38.997  8113-8113  Capacitor               dev...z.capacitor.firebaseauth.demo  D  Sending plugin error: {"save":false,"callbackId":"67029628","pluginId":"FirebaseAuthentication","methodName":"signInWithGoogle","success":false,"error":{"message":"10: "}}
2023-10-07 00:01:39.002  8113-8113  Capacitor/AppPlugin     dev...z.capacitor.firebaseauth.demo  D  Firing change: true
2023-10-07 00:01:39.002  8113-8113  Capacitor/AppPlugin     dev...z.capacitor.firebaseauth.demo  V  Notifying listeners for event appStateChange
2023-10-07 00:01:39.002  8113-8113  Capacitor/AppPlugin     dev...z.capacitor.firebaseauth.demo  D  No listeners found for event appStateChange
2023-10-07 00:01:39.002  8113-8113  Capacitor/AppPlugin     dev...z.capacitor.firebaseauth.demo  V  Notifying listeners for event resume
2023-10-07 00:01:39.002  8113-8113  Capacitor/AppPlugin     dev...z.capacitor.firebaseauth.demo  D  No listeners found for event resume
2023-10-07 00:01:39.002  8113-8113  Capacitor               dev...z.capacitor.firebaseauth.demo  D  App resumed
2023-10-07 00:01:39.263  8113-8113  Capacitor/Console       dev...z.capacitor.firebaseauth.demo  E  File: http://localhost/main.js - Line 744 - Msg: Error: Uncaught (in promise): Error: 10: 
                                                                                                    Error: 10: 
                                                                                                        at returnResult (http://localhost/:773:32)
                                                                                                        at win.androidBridge.onmessage (http://localhost/:748:21)
```

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04

**Smartphone (please complete the following information):**

- Android 10.0

**Comment by robingenz** [comment]
It seems that you have not solved the other problem: `java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process dev.robingenz.capacitor.firebaseauth.demo. Make sure to call FirebaseApp.initializeApp(Context) first.`

**Comment by ebadi** [comment]
> It seems that you have not solved the other problem: `java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process dev.robingenz.capacitor.firebaseauth.demo. Make sure to call FirebaseApp.initializeApp(Context) first.`

I am very sorry. It seems those messages were from previous session (I am new to Android Studio and mobile development), I don't get `IllegalStateException` anymore. I updated the issue.

**Comment by robingenz** [comment]
Okay, in this case you need to add your SHA-1 key to your Firebase project, see https://stackoverflow.com/a/49800546/6731412.

**Comment by ebadi** [comment]
Thanks the problem is solved. 
Here is what I did for others. I could not follow the instruction in the stackoverflow link above and I had issues with signing key before and resolved it like [this](https://github.com/robingenz/capacitor-firebase-authentication-demo/issues/218#issuecomment-1703769345)

keystore.properties
```
storePassword=123456789
keyPassword=123456789
keyAlias=debug
storeFile=debug.keystore
```

in android directory created by capacitor: `keytool -genkey -v -keystore debug.keystore -storepass 1234 -alias debug -keypass 1234 -keyalg RSA -keysize 2048 -validity 10000`

and I followed [this instruction](https://stackoverflow.com/a/71498554) to get the sha1: `keytool -list -v -keystore debug.keystore -alias debug -storepass 123456789 -keypass 123456789`

```
Command line args: [-list, -v, -keystore, debug.keystore, -alias, debug, -storepass, 123456789, -keypass, 123456789]
Alias name: debug
Creation date: Oct 6, 2023
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=test, OU=test, O=test, L=test, ST=test, C=eu
Issuer: CN=test, OU=test, O=test, L=test, ST=test, C=eu
Serial number: 5439b28
Valid from: Fri Oct 06 23:06:24 CEST 2023 until: Tue Feb 21 22:06:24 CET 2051
Certificate fingerprints:
	 SHA1: 63:A0:B7:60:2D:6E:4D:40:7A:C1:ED:90:56:05:FB:11:66:83:BA:93
	 SHA256: 78:23:4D:91:36:7A:DF:0E:68:4D:D8:CA:8B:3E:C8:D5:B3:56:F6:2B:76:8D:76:88:FF:8D:88:23:0A:84:59:B1
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 1B 27 43 27 9F AA 20 5F   A6 05 D4 44 14 CF 5E D0  .'C'.. _...D..^.
0010: 88 85 E6 72                                        ...r
]
]

```

Downloaded the new `google-services.json`  and it is now working without any issue.
Thank you so much @robingenz.
